name: Build (clang)
on:
  push:
    branches: [master, actions]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang
        run: apt-get update && apt-get install -y clang
      - name: Run tests
        run: |
          make CC=clang
          make check CC=clang
          ls -lh libtyche.so.0.1 tyche