#ifndef TYCHE_TYCHE_H
#define TYCHE_TYCHE_H

typedef enum {
    TT_NIL, TT_INTEGER, TT_REAL, TT_STRING, TT_STRING_CONST, TT_ARRAY, TT_TABLE, TT_FUNCTION, TT_NATIVE_PTR,
} TYC_TYPE;

#endif //TYCHE_TYCHE_H
