#ifndef TYCHE_TYCHE_H
#define TYCHE_TYCHE_H

typedef enum {
    TT_NIL, TT_INTEGER, TT_REAL, TT_STRING, TT_STRING_CONST, TT_ARRAY, TT_TABLE, TT_FUNCTION, TT_NATIVE_PTR,
} TYC_TYPE;

typedef enum {
    T_OK = 0,
    T_ERR_STACK_UNDERFLOW = -1, T_ERR_STACK_FP_UNDERFLOW = -2, T_ERR_STACK_ACCESS_OUT_OF_RANGE = -3,
    T_ERR_HEAP_KEY_NOT_FOUND = -10,
    T_ERR_TABLE_KEY_NOT_FOUND = -20,
    T_ERR_ASSEMBLER_SYNTAX_ERROR = -30,
} TYC_RESULT;

#endif //TYCHE_TYCHE_H
